# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import data.protof.message_pb2 as message__pb2


class MsgServiceStub(object):
    """сервер, который необходимо поднять 
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetMsg = channel.unary_unary(
                '/MsgService/GetMsg',
                request_serializer=message__pb2.MsgRequest.SerializeToString,
                response_deserializer=message__pb2.MsgResponse.FromString,
                )
        self.Send = channel.unary_unary(
                '/MsgService/Send',
                request_serializer=message__pb2.SendRequest.SerializeToString,
                response_deserializer=message__pb2.MsgResponse.FromString,
                )


class MsgServiceServicer(object):
    """сервер, который необходимо поднять 
    """

    def GetMsg(self, request, context):
        """rpc GetMsg (MsgRequest) returns (stream MsgResponse){}

        GetMsg - метод реализованный на клиенте, которые отправляет запрос и возвращает ответ
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Send(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MsgServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetMsg': grpc.unary_unary_rpc_method_handler(
                    servicer.GetMsg,
                    request_deserializer=message__pb2.MsgRequest.FromString,
                    response_serializer=message__pb2.MsgResponse.SerializeToString,
            ),
            'Send': grpc.unary_unary_rpc_method_handler(
                    servicer.Send,
                    request_deserializer=message__pb2.SendRequest.FromString,
                    response_serializer=message__pb2.MsgResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'MsgService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class MsgService(object):
    """сервер, который необходимо поднять 
    """

    @staticmethod
    def GetMsg(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/MsgService/GetMsg',
            message__pb2.MsgRequest.SerializeToString,
            message__pb2.MsgResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Send(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/MsgService/Send',
            message__pb2.SendRequest.SerializeToString,
            message__pb2.MsgResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
