# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: message.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rmessage.proto\"*\n\nMsgRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0e\n\x06number\x18\x02 \x01(\x05\".\n\x0bMsgResponse\x12\x0e\n\x06status\x18\x01 \x01(\x05\x12\x0f\n\x07\x64\x65tails\x18\x02 \x01(\t\"E\n\x0bSendRequest\x12\x11\n\ttableName\x18\x01 \x01(\t\x12\x11\n\tbase64Str\x18\x02 \x01(\t\x12\x10\n\x08sourceId\x18\x03 \x01(\t2Y\n\nMsgService\x12%\n\x06GetMsg\x12\x0b.MsgRequest\x1a\x0c.MsgResponse\"\x00\x12$\n\x04Send\x12\x0c.SendRequest\x1a\x0c.MsgResponse\"\x00\x62\x06proto3')



_MSGREQUEST = DESCRIPTOR.message_types_by_name['MsgRequest']
_MSGRESPONSE = DESCRIPTOR.message_types_by_name['MsgResponse']
_SENDREQUEST = DESCRIPTOR.message_types_by_name['SendRequest']
MsgRequest = _reflection.GeneratedProtocolMessageType('MsgRequest', (_message.Message,), {
  'DESCRIPTOR' : _MSGREQUEST,
  '__module__' : 'message_pb2'
  # @@protoc_insertion_point(class_scope:MsgRequest)
  })
_sym_db.RegisterMessage(MsgRequest)

MsgResponse = _reflection.GeneratedProtocolMessageType('MsgResponse', (_message.Message,), {
  'DESCRIPTOR' : _MSGRESPONSE,
  '__module__' : 'message_pb2'
  # @@protoc_insertion_point(class_scope:MsgResponse)
  })
_sym_db.RegisterMessage(MsgResponse)

SendRequest = _reflection.GeneratedProtocolMessageType('SendRequest', (_message.Message,), {
  'DESCRIPTOR' : _SENDREQUEST,
  '__module__' : 'message_pb2'
  # @@protoc_insertion_point(class_scope:SendRequest)
  })
_sym_db.RegisterMessage(SendRequest)

_MSGSERVICE = DESCRIPTOR.services_by_name['MsgService']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _MSGREQUEST._serialized_start=17
  _MSGREQUEST._serialized_end=59
  _MSGRESPONSE._serialized_start=61
  _MSGRESPONSE._serialized_end=107
  _SENDREQUEST._serialized_start=109
  _SENDREQUEST._serialized_end=178
  _MSGSERVICE._serialized_start=180
  _MSGSERVICE._serialized_end=269
# @@protoc_insertion_point(module_scope)
